#!/bin/bash
# Скрипт для деплоймента на Render (бэкенд)

echo "🚀 Деплоймент бэкенда на Render..."
echo ""
echo "📝 Инструкции:"
echo ""
echo "1️⃣ Откройте https://render.com"
echo ""
echo "2️⃣ Создайте новый Web Service:"
echo "   - Нажмите 'New +' → 'Web Service'"
echo "   - Подключите ваш GitHub репозиторий"
echo "   - Выберите ветку 'main'"
echo ""
echo "3️⃣ Настройки:"
echo "   - Name: orca-clicker-api"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: node websocket-server.js"
echo "   - Instance Type: Free (или выше для production)"
echo ""
echo "4️⃣ Переменные окружения (Environment):"
echo "   - NODE_ENV: production"
echo "   - PORT: 3001"
echo "   - FRONTEND_URL: https://your-vercel-app.vercel.app"
echo ""
echo "5️⃣ Нажмите 'Create Web Service'"
echo ""
echo "⏳ Ожидание деплоймента (~1-2 минуты)..."
echo ""
echo "✅ После успешного деплоймента:"
echo "   - Скопируйте URL сервиса (например: https://orca-clicker-api.onrender.com)"
echo "   - Используйте его для VITE_WS_URL в переменных Vercel"
echo ""
echo "💡 Совет:"
echo "   Render бесплатно спит сервис если нет активности 15 минут."
echo "   Первый запрос может занять 30 секунд."
