#!/bin/bash
# Скрипт для деплоймента на Vercel (фронтенд)

echo "🚀 Деплоймент фронтенда на Vercel..."
echo ""
echo "⚠️ Важно: Сначала задеплойте бэкенд на Render!"
echo ""
echo "📝 Инструкции:"
echo ""
echo "1️⃣ Откройте https://vercel.com"
echo ""
echo "2️⃣ Создайте новый проект:"
echo "   - Нажмите 'Add New' → 'Project'"
echo "   - Выберите ваш GitHub репозиторий"
echo "   - Нажмите 'Import'"
echo ""
echo "3️⃣ Настройки проекта:"
echo "   - Framework Preset: Other (не React/Next.js)"
echo "   - Root Directory: ./"
echo "   - Build Command: (оставьте пусто - используется vercel.json)"
echo "   - Output Directory: (оставьте пусто)"
echo ""
echo "4️⃣ Переменные окружения (Environment Variables):"
echo "   Нажмите 'Environment Variables' и добавьте:"
echo ""
echo "   VITE_WS_URL: wss://orca-clicker-api.onrender.com"
echo "              (замените на ваш URL с Render)"
echo ""
echo "5️⃣ Нажмите 'Deploy'"
echo ""
echo "⏳ Ожидание деплоймента (~2-3 минуты)..."
echo ""
echo "✅ После успешного деплоймента:"
echo "   - Скопируйте URL фронтенда (например: https://orca-clicker.vercel.app)"
echo "   - Обновите FRONTEND_URL переменную в Render"
echo ""
echo "💡 Совет:"
echo "   Vercel автоматически перестраивает проект при каждом push в main"
echo ""
echo "🧪 Тестирование:"
echo "   - Откройте URL Vercel"
echo "   - Создайте новый аккаунт"
echo "   - Проверьте что данные сохраняются"
